[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
depends = ['neocomplete.vim']
hook_source = '''
  autocmd FileType python setlocal omnifunc=jedi#completions
  autocmd FileType python setlocal completeopt-=preview
  let g:jedi#completions_enabled = 0
  let g:jedi#auto_vim_configuration = 0
  let g:jedi#show_call_signatures = 0
  let g:jedi#smart_auto_mappings = 0
  let g:neocomplete#force_omni_input_patterns.python = '\h\w*\|[^. \t]\.\w*'
'''

[[plugins]]
repo = 'ujihisa/neco-look'
on_ft = 'tex'

[[plugins]]
repo = 'Mizuchi/STL-Syntax'
on_ft = 'cpp'

[[plugins]]
repo = 'justmao945/vim-clang'
on_ft = 'cpp'
hook_source = '''
  "clang-vim c++11 
  if executable('clang-4.0')
    let g:clang_exec = 'clang-4.0'
  elseif executable('clang-3.7')
    let g:clang_exec = 'clang-3.7'
  elseif executable('clang-3.6')
    let g:clang_exec = 'clang-3.6'
  elseif executable('clang-3.5')
    let g:clang_exec = 'clang-3.5'
  elseif executable('clang-3.4')
    let g:clang_exec = 'clang-3.4'
  elseif executable('clang40')
    let g:clang_exec = 'clang40'
  elseif executable('clang37')
    let g:clang_exec = 'clang37'
  elseif executable('clang36')
    let g:clang_exec = 'clang36'
  elseif executable('clang35')
    let g:clang_exec = 'clang35'
  else
    let g:clang_exec = 'clang'
  endif
  let g:clang_cpp_options = '-std=c++14'
  " disable auto completion for vim-clang
  let g:clang_auto = 0
  let g:clang_diagsopt = ''
  " default 'longest' can not work with neocomplete
  let g:clang_c_completeopt = 'menuone'
  let g:clang_cpp_completeopt = 'menuone'
'''
